apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "axiom-backend.fullname" . }}
  labels:
    {{- include "axiom-backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "axiom-backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "axiom-backend.selectorLabels" . | nindent 8}}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "axiom-backend.fullname" . }}-sa
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ .Values.config.name }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
