kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    cert-manager.io/issuer-group: cert.dana.io
    cert-manager.io/issuer-kind: ClusterIssuer
    cert-manager.io/issuer-name: {{ .Values.route.issuer }}
    cert-manager.io/private-key-algorithm: RSA
    cert-manager.io/private-key-size: '4096'
    cert-manager.io/renew-before: 30m
  name: {{ .Chart.Name }}
  namespace: {{ .Release.namespace }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "axiom-backend.fullname" . }}
    weight: 100
  port:
    targetPort: https
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None